### ISSUE TITLE
Customer is unable to view or download invoice

### ISSUE THREAD

**Issue by michelleperham** [TypeNetwork/status.typenetwork.com#2]
Customer: alyssa.buckley@sunlife.com

I'm unable to repro, but she ran into this when trying to view an old invoice:
![screen shot 2017-09-19 at 2 02 13 pm](https://user-images.githubusercontent.com/19579755/30608001-d5132b80-9d2b-11e7-85c2-55044d2f6a0f.png)

**Comment by konistehrad** [comment]
@michelleperham good morning! This repo is for the status page only; I'm going to move this ticket over to https://github.com/TypeNetwork/typenetwork.com/issues. Thanks!
