### ISSUE TITLE
Customer is having trouble with renewal

### ISSUE THREAD

**Issue by michelleperham** [TypeNetwork/status.typenetwork.com#4]
Removed.

**Comment by michelleperham** [comment]
Update: Their credit card was on file and I just got this to go through. I'm not sure why they were having so much trouble previously.

**Comment by konistehrad** [comment]
Morning @michelleperham! I've migrated this over to https://github.com/TypeNetwork/typenetwork.com/issues/3773. Issues here will not be seen by the core TN developers; to report issues please use https://github.com/TypeNetwork/typenetwork.com/issues/new. Thanks again!
